import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Polymesh Staking Stats</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div>
        <h1> Homepage</h1>
        <p>This is the home page</p>
        <Link href='/stakingCharts'>
          <a className={styles.btn}>Staking Charts</a>
        </Link>
        <Link href='/page2'>
          <a className={styles.btn}>Page 2</a>
        </Link>
      </div>
    </>
  );
};

export default Home;
