import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Polymesh Staking Stats</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div>
        <h1> Homepage</h1>
        <p>This is the home page. Not much to see here.</p>
        <Link href='/overview-charts'>
          <a className={styles.btn}>Overview Charts</a>
        </Link>
        <Link href='/operator-charts'>
          <a className={styles.btn}>Operator Charts</a>
        </Link>
        <Link href='/operator-info'>
          <a className={styles.btn}>Operator Info</a>
        </Link>
      </div>
    </>
  );
};

export default Home;
